---
name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ["1.17", "1.18"]
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Run install script
        run: |
          chmod +x scripts/install.sh
          ./scripts/install.sh

      - name: Run with empty args
        run: $HOME/.local/bin/indiepkg

      - name: Run help command
        run: $HOME/.local/bin/indiepkg help

      - name: Run setup command
        run: $HOME/.local/bin/indiepkg setup -d

      - name: Run github-gen command
        continue-on-error: true
        run: $HOME/.local/bin/indiepkg github-gen talwat indiepkg -d

      - name: Install a few packages
        run: $HOME/.local/bin/indiepkg install pfetch yaf neofetch -y -d

      - name: Test installed packages
        run: |
          $HOME/.local/bin/pfetch
          $HOME/.local/bin/yaf

      - name: Force upgrade packages
        run: |
          $HOME/.local/bin/indiepkg upgrade -f -d
          $HOME/.local/bin/indiepkg upgrade pfetch yaf neofetch -f -d

      - name: Update packages
        run: |
          $HOME/.local/bin/indiepkg update -d
          $HOME/.local/bin/indiepkg upgrade pfetch yaf neofetch -d

      - name: Add repo
        run: $HOME/.local/bin/indiepkg repo add https://raw.githubusercontent.com/talwat/indiepkg/main/packages/linux-only/

      - name: List repos
        run: $HOME/.local/bin/indiepkg repo list

      - name: Test querying
        continue-on-error: true
        run: $HOME/.local/bin/indiepkg search fetch

      - name: Try installing package from linux-only
        run: $HOME/.local/bin/indiepkg install katfetch -y -d

      - name: List packages
        run: $HOME/.local/bin/indiepkg list

      - name: Uninstall package with --purge
        run: $HOME/.local/bin/indiepkg uninstall neofetch -p -y

      - name: Uninstall other packages
        run: $HOME/.local/bin/indiepkg uninstall pfetch yaf -y -d

      - name: Try other commands
        run: |
          $HOME/.local/bin/indiepkg sync
          $HOME/.local/bin/indiepkg info btop
          $HOME/.local/bin/indiepkg remove-data btop -y -d
          $HOME/.local/bin/indiepkg version

      - name: Try manually updating IndiePKG
        run: |
          $HOME/.local/bin/indiepkg indiepkg-update
